spring:
  application:
    name: image-service

  data:
    mongodb:
      uri: mongodb://root:example@db-mongodb:27017/image_service_db?authSource=admin

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: image-service-group

security:
  jwt:
    secret: ${JWT_SECRET:default-secret}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
